# TensorFlow Playground

A notebook for experimenting with TensorFlow and machine learning models.

In [2]:
# Import Required Libraries
import tensorflow as tf
import numpy as np
import pandas as pd

print(f"TensorFlow version: {tf.__version__}")

TensorFlow version: 2.20.0


In [6]:
# TensorFlow 2.x Example
hello = tf.constant("Hello, TensorFlow!")
# print(hello)

# You can also print the numpy value directly
print(hello.numpy())
print(hello)

b'Hello, TensorFlow!'
tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)


In [10]:
import numpy as np

newArr=np.array([1, 2, 3])
arr=np.arange(10)
print(arr)
print(newArr)
print(type(newArr))


[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
arr=np.array([1, 2, 3,6,7,31,23])
arr.reshape(7,1)
arr

array([ 1,  2,  3,  6,  7, 31, 23])

In [17]:
mat=np.arange(100).reshape(10,10)
print(mat)
print(mat[0,1])
print(mat[:, 0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
1
[ 0 10 20 30 40 50 60 70 80 90]
