In [19]:
## Learning python
import numpy as np
np.random.seed(0)
matrix = np.random.randint(1, 10, size=(3, 3))
# Set seed for reproducibility
matrix1 = np.random.randint(1, 10, size=(3, 3))
print(matrix)

print("---***---") 
print(matrix1)

print("---***---")

# Correct way to create a numpy array from a list of lists
matrix2 = np.array([[1, 2, 3], [1, 2, 3]])
print(matrix2)

print("---***---")

twoDArr=np.array([[1,2,3], [5,6,7]])
## first two rows and columns
print(twoDArr[:2, :2])

print("---***---")

##second column
print(twoDArr[:, 1])

def relu(x): 
    return np.maximum(x, 0)

def sigmoid(x): 
    return 1 / (1+np.exp(-x))

x = np.array([-1, 0, 1, 2])
print("---***---")
print(relu(x))
print("---***---")
print(sigmoid(x))

print("---***---")
x1 = np.array([2, 0, 1, 0.1])
def softmax(x): 
    expX=np.exp(x)
    return expX/np.sum(expX)
print(softmax(x1))

print("---***---")
def msl(yPred, yTrue):
    return np.mean((yTrue-yPred)**2)

yTrue=np.array([2,3,4])
yPred=np.array([1,3.5,5])

print(msl(yPred, yTrue))

print("---***---")

def crossEntropy(prob, trueClass):
    return -np.log(prob[trueClass])

prob = np.array([0.1, 0.4, 0.5])
print(crossEntropy(prob, 2))



[[6 1 4]
 [4 8 4]
 [6 3 5]]
---***---
[[8 7 9]
 [9 2 7]
 [8 8 9]]
---***---
[[1 2 3]
 [1 2 3]]
---***---
[[1 2]
 [5 6]]
---***---
[2 6]
---***---
[0 0 1 2]
---***---
[0.26894142 0.5        0.73105858 0.88079708]
---***---
[0.60503998 0.08188326 0.22258177 0.09049499]
---***---
0.75
---***---
0.6931471805599453


In [ ]:
import numpy as np


In [27]:
import numpy as np
## y=8x+2
x=np.array([1,4,5], dtype=float)
y=np.array([10,34,42], dtype=float)
n=len(x)

m=0.0
c=0.0
# epochs=1
learingRate=0.01
epochs = 1000

for epoch in range(epochs):
    ## forward pass
    yPred=m*x + c

    ## mse loss
    loss = np.mean((yPred-y)**2)

    ## dloss/da
    dm = (2/n)*np.sum((yPred-y)*x)
    dc = (2/n)*np.sum(yPred-y)

    m = m - (dm*learingRate)
    c = c - (dc*learingRate)

    print(f"Epoch : {epoch}")
    print(f"Epoch : {epoch}, curr losss {loss:0.6f}")

print(f"Final m is {m:0.6f}")
print(f"Final c is {c:0.6f}")


def accuracy(yPred, yTrue):
    n=len(yPred)
    correct=np.sum(yPred==yTrue)
    return correct/n

yPred=np.array([1,2,3,2,1])
yTrue=np.array([1,1,2,3,1])

print(f"Accuracy is {accuracy(yPred, yTrue)}")


Epoch : 0
Epoch : 0, curr losss 1006.666667
Epoch : 1
Epoch : 1, curr losss 498.782519
Epoch : 2
Epoch : 2, curr losss 247.136637
Epoch : 3
Epoch : 3, curr losss 122.451409
Epoch : 4
Epoch : 4, curr losss 60.672507
Epoch : 5
Epoch : 5, curr losss 30.062361
Epoch : 6
Epoch : 6, curr losss 14.895677
Epoch : 7
Epoch : 7, curr losss 7.380901
Epoch : 8
Epoch : 8, curr losss 3.657485
Epoch : 9
Epoch : 9, curr losss 1.812608
Epoch : 10
Epoch : 10, curr losss 0.898508
Epoch : 11
Epoch : 11, curr losss 0.445587
Epoch : 12
Epoch : 12, curr losss 0.221171
Epoch : 13
Epoch : 13, curr losss 0.109975
Epoch : 14
Epoch : 14, curr losss 0.054876
Epoch : 15
Epoch : 15, curr losss 0.027573
Epoch : 16
Epoch : 16, curr losss 0.014042
Epoch : 17
Epoch : 17, curr losss 0.007335
Epoch : 18
Epoch : 18, curr losss 0.004008
Epoch : 19
Epoch : 19, curr losss 0.002357
Epoch : 20
Epoch : 20, curr losss 0.001536
Epoch : 21
Epoch : 21, curr losss 0.001127
Epoch : 22
Epoch : 22, curr losss 0.000921
Epoch : 23
Epoch : 

In [42]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

print(torch.__version__)


numbers = [1, 2, 3, 4, [1,2]]
print(numbers.__len__())

image_shape = (3, 224, 224)
print(image_shape)

class MyClass: 
    def __init__(self, name): 
        self.name = name
    def print_name(self): 
        print(f"Class name is {self.name}")

myObj = MyClass("MyClass")
myObj.print_name()


print("-----")
x=torch.tensor([1,2,3])
yRandomNormal=torch.randn(3,4)
yRandomNormalNew=torch.randn((3,4))
yRandom=torch.rand(3,4)
print("yRandomNormal is ", yRandomNormal)
print("yRandom is ", yRandom)
print("yRandomNormalNew is ", yRandomNormalNew)


y=torch.arange(12)
yView=y.view(3,4)
yReshape=y.reshape(3,4)
print("y is ", y)
print("yView is ", yView)
print("yReshape is ", yReshape)


yNormal = torch.tensor([1,3,4])
print("yNormal is ", yNormal)
print("yNormalShape is ", yNormal.shape)
yUnsquueeze = yNormal.unsqueeze(0)
print("yUnsquueeze is ", yUnsquueeze)
print("yUnsquueeze shape is ", yUnsquueeze.shape)

## permutation
yNormal1 = torch.randn((1,2,3))
yPermute = yNormal1.permute(2, 1, 0)
## should be 4,3,1
print("yPermute is ", yPermute.shape)

## define a and b tensors and then use a@b to find the tensor multiplication
a = torch.randn((2,3))
b = torch.randn((3,4))
c = a@b
print("a is ", a)
print("b is ", b)   
print("c is ", c)

2.8.0
5
(3, 224, 224)
Class name is MyClass
-----
yRandomNormal is  tensor([[-0.0876, -0.9965, -0.4915,  0.7458],
        [ 0.2351,  0.9550, -0.4463, -1.6808],
        [ 1.0962, -0.4615, -1.2009,  0.4231]])
yRandom is  tensor([[0.2780, 0.1491, 0.9811, 0.9047],
        [0.0770, 0.4909, 0.4317, 0.8603],
        [0.3096, 0.4707, 0.2252, 0.5289]])
yRandomNormalNew is  tensor([[-0.4708, -0.4364, -1.2363, -1.4934],
        [-2.2418,  1.8301, -1.5089,  0.7611],
        [-1.0217,  2.2840,  0.3784, -0.1050]])
y is  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
yView is  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
yReshape is  tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
yNormal is  tensor([1, 3, 4])
yNormalShape is  torch.Size([3])
yUnsquueeze is  tensor([[1, 3, 4]])
yUnsquueeze shape is  torch.Size([1, 3])
yPermute is  torch.Size([3, 2, 1])
a is  tensor([[-1.4942, -1.5243, -1.5074],
        [-0.0964, -0.7589,  0.71

In [1]:
import torch

x=torch.tensor([1,2,3], dtype=torch.float32)
y=torch.tensor([12,20,28], dtype=torch.float32)
## y= 8x+4(y=mx+c)
m=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
c=torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

epochs=1000
learningRate=0.01
for i in range(epochs):
    ## forward pass
    yPred=m*x + c

    ## mse loss
    loss = torch.mean((yPred-y)**2)

    ## backward pass
    loss.backward()

    ## update weights
    with torch.no_grad():
        m -= learningRate*m.grad
        c -= learningRate*c.grad

        ## zero the gradients after updating weights
        m.grad.zero_()
        c.grad.zero_()

    print(f"Epoch : {i}, curr losss {loss:0.6f}")

print(f"Final m is {m:0.6f}")
print(f"Final c is {c:0.6f}")

Epoch : 0, curr losss 442.666656
Epoch : 1, curr losss 349.909088
Epoch : 2, curr losss 276.589142
Epoch : 3, curr losss 218.633667
Epoch : 4, curr losss 172.822922
Epoch : 5, curr losss 136.611954
Epoch : 6, curr losss 107.989098
Epoch : 7, curr losss 85.364235
Epoch : 8, curr losss 67.480461
Epoch : 9, curr losss 53.344299
Epoch : 10, curr losss 42.170368
Epoch : 11, curr losss 33.337963
Epoch : 12, curr losss 26.356394
Epoch : 13, curr losss 20.837816
Epoch : 14, curr losss 16.475668
Epoch : 15, curr losss 13.027591
Epoch : 16, curr losss 10.302053
Epoch : 17, curr losss 8.147634
Epoch : 18, curr losss 6.444661
Epoch : 19, curr losss 5.098532
Epoch : 20, curr losss 4.034466
Epoch : 21, curr losss 3.193357
Epoch : 22, curr losss 2.528490
Epoch : 23, curr losss 2.002920
Epoch : 24, curr losss 1.587468
Epoch : 25, curr losss 1.259054
Epoch : 26, curr losss 0.999440
Epoch : 27, curr losss 0.794209
Epoch : 28, curr losss 0.631965
Epoch : 29, curr losss 0.503701
Epoch : 30, curr losss 0.4

### Notes

- `np.random.seed(0)` fixes the random sequence but each call to a random function consumes values from that sequence. So `matrix` and `matrix1` will be different, but reproducible across runs.
- Use `np.array(...)` (or `np.asarray(...)`) to create arrays from Python lists. `np.ndarray(...)` is a low-level constructor that expects a `shape` argument and raw uninitialized memory; passing a Python list to it will raise an error or behave unexpectedly.

Examples:

- Recommended: `matrix2 = np.array([[1,2,3],[1,2,3]])`  # works
- Avoid: `matrix2 = np.ndarray([[1,2,3],[1,2,3]])`  # incorrect usage

In [1]:
import torch 

x=torch.tensor([-1.0, 1.0, -2.0, 0.0, 2.0])
reluOutput=torch.relu(x)

y=torch.tensor([-1.0, 1.0, -2.0, 0.0, 2.0])
sigmoidOutput=torch.sigmoid(y)

z=torch.tensor([-1.0, 1.0, -2.0, 0.0, 2.0])
tanhOutput=torch.tanh(z)

print(reluOutput)
print(sigmoidOutput)
print(tanhOutput)

logits=torch.tensor([0.1, 0.2, 0.3])
softmaxOutput=torch.softmax(logits, dim=0)
print(softmaxOutput)

tensor([0., 1., 0., 0., 2.])
tensor([0.2689, 0.7311, 0.1192, 0.5000, 0.8808])
tensor([-0.7616,  0.7616, -0.9640,  0.0000,  0.9640])
tensor([0.3006, 0.3322, 0.3672])


In [4]:
import torch
from torch.utils.data import DataLoader, Dataset
## Define a custom dataset
class MyDataset(Dataset):
    def __init__(self):
        self.data = torch.randn(4, 3)
        self.labels = ((self.data[:, 0] + self.data[:, 1]) > 0).long()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]
    
myData = MyDataset()
print(f"Length of dataset: {len(myData)}")
print(f"Sample data: {myData.data}")

sampleX, sampleY = myData[0]
print(f"Sample data: {sampleX}, Sample label: {sampleY}")

dataLoader = DataLoader(myData, batch_size=2, shuffle=True)

for batchX, batchY in dataLoader:
    print(f"Batch data: {batchX}, Batch labels: {batchY}")



Length of dataset: 4
Sample data: tensor([[ 0.5955,  0.4713,  0.2356],
        [-0.1697,  1.7357, -0.9744],
        [ 0.1274,  1.5033, -0.3471],
        [-0.1703,  0.3127, -1.9392]])
Sample data: tensor([0.5955, 0.4713, 0.2356]), Sample label: 1
Batch data: tensor([[ 0.1274,  1.5033, -0.3471],
        [-0.1697,  1.7357, -0.9744]]), Batch labels: tensor([1, 1])
Batch data: tensor([[ 0.5955,  0.4713,  0.2356],
        [-0.1703,  0.3127, -1.9392]]), Batch labels: tensor([1, 1])


CNN

In [5]:
import torch
import torch.nn as nn

conv = nn.Conv2d(in_channels=3, out_channels=16, kernel_size=3, stride=1, padding=1)
input_tensor = torch.randn(1, 3, 32, 32)
output_tensor = conv(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output_tensor.shape}")

Input shape: torch.Size([1, 3, 32, 32])
Output shape: torch.Size([1, 16, 32, 32])


import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader


# -----------------------------
# 1. Load and preprocess MNIST
# -----------------------------

transform = transforms.ToTensor()

train_dataset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.MNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)


# -----------------------------
# 2. Create batches
# -----------------------------

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=64,
    shuffle=False
)


# -----------------------------
# 3. Define CNN
# -----------------------------

model = nn.Sequential(

    nn.Conv2d(
        in_channels=1,
        out_channels=16,
        kernel_size=3,
        padding=1
    ),

    nn.ReLU(),

    nn.MaxPool2d(
        kernel_size=2,
        stride=2
    ),

    nn.Conv2d(
        in_channels=16,
        out_channels=32,
        kernel_size=3,
        padding=1
    ),

    nn.ReLU(),

    nn.MaxPool2d(
        kernel_size=2,
        stride=2
    ),

    nn.Flatten(),

    nn.Linear(
        32 * 7 * 7,
        10
    )
)


# -----------------------------
# 4. Loss + optimizer
# -----------------------------

criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)


# -----------------------------
# 5. Training
# -----------------------------

for epoch in range(5):

    model.train()

    for images, labels in train_loader:

        # Forward pass
        outputs = model(images)

        # Calculate loss
        loss = criterion(outputs, labels)

        # Clear previous gradients
        optimizer.zero_grad()

        # Backpropagation
        loss.backward()

        # Update weights
        optimizer.step()

    print(
        f"Epoch {epoch + 1}, "
        f"Loss: {loss.item():.4f}"
    )


# -----------------------------
# 6. Testing
# -----------------------------

model.eval()

correct = 0
total = 0

with torch.no_grad():

    for images, labels in test_loader:

        outputs = model(images)

        predictions = outputs.argmax(dim=1)

        total += labels.size(0)

        correct += (
            predictions == labels
        ).sum().item()


accuracy = correct / total

print(
    f"Test Accuracy: {accuracy * 100:.2f}%"
)
