In [19]:
## Learning python
import numpy as np
np.random.seed(0)
matrix = np.random.randint(1, 10, size=(3, 3))
# Set seed for reproducibility
matrix1 = np.random.randint(1, 10, size=(3, 3))
print(matrix)

print("---***---") 
print(matrix1)

print("---***---")

# Correct way to create a numpy array from a list of lists
matrix2 = np.array([[1, 2, 3], [1, 2, 3]])
print(matrix2)

print("---***---")

twoDArr=np.array([[1,2,3], [5,6,7]])
## first two rows and columns
print(twoDArr[:2, :2])

print("---***---")

##second column
print(twoDArr[:, 1])

def relu(x): 
    return np.maximum(x, 0)

def sigmoid(x): 
    return 1 / (1+np.exp(-x))

x = np.array([-1, 0, 1, 2])
print("---***---")
print(relu(x))
print("---***---")
print(sigmoid(x))

print("---***---")
x1 = np.array([2, 0, 1, 0.1])
def softmax(x): 
    expX=np.exp(x)
    return expX/np.sum(expX)
print(softmax(x1))

print("---***---")
def msl(yPred, yTrue):
    return np.mean((yTrue-yPred)**2)

yTrue=np.array([2,3,4])
yPred=np.array([1,3.5,5])

print(msl(yPred, yTrue))

print("---***---")

def crossEntropy(prob, trueClass):
    return -np.log(prob[trueClass])

prob = np.array([0.1, 0.4, 0.5])
print(crossEntropy(prob, 2))



[[6 1 4]
 [4 8 4]
 [6 3 5]]
---***---
[[8 7 9]
 [9 2 7]
 [8 8 9]]
---***---
[[1 2 3]
 [1 2 3]]
---***---
[[1 2]
 [5 6]]
---***---
[2 6]
---***---
[0 0 1 2]
---***---
[0.26894142 0.5        0.73105858 0.88079708]
---***---
[0.60503998 0.08188326 0.22258177 0.09049499]
---***---
0.75
---***---
0.6931471805599453


In [24]:
import numpy as np
## y=8x+2
x=np.array([1,4,5], dtype=float)
y=np.array([10,34,42], dtype=float)
n=len(x)

m=0.0
c=0.0
# epochs=1
learingRate=0.01
epochs = 1000

for epoch in range(epochs):
    ## forward pass
    yPred=m*x + c

    ## mse loss
    loss = np.mean((yPred-y)**2)

    ## dloss/da
    dm = (2/n)*np.sum((yPred-y)*x)
    dc = (2/n)*np.sum(yPred-y)

    m = m - (dm*learingRate)
    c = c - (dc*learingRate)

    print(f"Epoch : {epoch}")
    print(f"Epoch : {epoch}, curr losss {loss:0.6f}")

print(f"Final m is {m:0.6f}")
print(f"Final c is {c:0.6f}")

Epoch : 0
Epoch : 0, curr losss 1006.666667
Epoch : 1
Epoch : 1, curr losss 498.782519
Epoch : 2
Epoch : 2, curr losss 247.136637
Epoch : 3
Epoch : 3, curr losss 122.451409
Epoch : 4
Epoch : 4, curr losss 60.672507
Epoch : 5
Epoch : 5, curr losss 30.062361
Epoch : 6
Epoch : 6, curr losss 14.895677
Epoch : 7
Epoch : 7, curr losss 7.380901
Epoch : 8
Epoch : 8, curr losss 3.657485
Epoch : 9
Epoch : 9, curr losss 1.812608
Epoch : 10
Epoch : 10, curr losss 0.898508
Epoch : 11
Epoch : 11, curr losss 0.445587
Epoch : 12
Epoch : 12, curr losss 0.221171
Epoch : 13
Epoch : 13, curr losss 0.109975
Epoch : 14
Epoch : 14, curr losss 0.054876
Epoch : 15
Epoch : 15, curr losss 0.027573
Epoch : 16
Epoch : 16, curr losss 0.014042
Epoch : 17
Epoch : 17, curr losss 0.007335
Epoch : 18
Epoch : 18, curr losss 0.004008
Epoch : 19
Epoch : 19, curr losss 0.002357
Epoch : 20
Epoch : 20, curr losss 0.001536
Epoch : 21
Epoch : 21, curr losss 0.001127
Epoch : 22
Epoch : 22, curr losss 0.000921
Epoch : 23
Epoch : 

In [ ]:
import torch
print(torch.__version__)


numbers = [1, 2, 3, 4, [1,2]]
print(numbers.__len__())

image_shape = (3, 224, 224)
print(image_shape)

class MyClass: 
    def __init__(self, name): 
        self.name = name
    def print_name(self): 
        print(f"Class name is {self.name}")

myObj = MyClass("MyClass")
myObj.print_name()



2.8.0
5
(3, 224, 224)
Class name is MyClass


### Notes

- `np.random.seed(0)` fixes the random sequence but each call to a random function consumes values from that sequence. So `matrix` and `matrix1` will be different, but reproducible across runs.
- Use `np.array(...)` (or `np.asarray(...)`) to create arrays from Python lists. `np.ndarray(...)` is a low-level constructor that expects a `shape` argument and raw uninitialized memory; passing a Python list to it will raise an error or behave unexpectedly.

Examples:

- Recommended: `matrix2 = np.array([[1,2,3],[1,2,3]])`  # works
- Avoid: `matrix2 = np.ndarray([[1,2,3],[1,2,3]])`  # incorrect usage